# Generated by Django 4.2.30 on 2026-09-24 10:24

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # 测试库由迁移自动创建 PostGIS 扩展（CREATE EXTENSION IF NOT EXISTS）
        CreateExtension("postgis"),
        migrations.CreateModel(
            name='CleaningContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='合同编号')),
                ('contractor_name', models.CharField(max_length=128, verbose_name='承包商名称')),
                ('valid_from', models.DateTimeField(verbose_name='责任开始时间（含）')),
                ('valid_to', models.DateTimeField(verbose_name='责任结束时间（不含）')),
            ],
            options={
                'verbose_name': '保洁合同',
                'verbose_name_plural': '保洁合同',
            },
        ),
        migrations.CreateModel(
            name='EvidencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('image', models.ImageField(upload_to='evidence/%Y/%m/%d', verbose_name='图片文件')),
                ('phash', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='感知哈希(hex)')),
                ('captured_at', models.DateTimeField(verbose_name='拍摄时间')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='拍摄位置')),
                ('uploader', models.CharField(blank=True, default='', max_length=64, verbose_name='上传人')),
                ('note', models.CharField(blank=True, max_length=256, verbose_name='备注')),
            ],
            options={
                'verbose_name': '证据照片',
                'verbose_name_plural': '证据照片',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('penalty_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='处罚单号')),
                ('contractor_name', models.CharField(blank=True, max_length=128, verbose_name='责任承包商快照')),
                ('points', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='当前有效扣分')),
                ('escalation_level', models.PositiveSmallIntegerField(default=0, verbose_name='逾期升级等级')),
                ('status', models.CharField(choices=[('draft', '待复核'), ('locked', '已锁定')], default='draft', max_length=16, verbose_name='状态')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='assessment.cleaningcontract', verbose_name='责任合同快照')),
            ],
            options={
                'verbose_name': '处罚单元',
                'verbose_name_plural': '处罚单元',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='版本号')),
                ('points', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='扣分')),
                ('escalation_level', models.PositiveSmallIntegerField(default=0, verbose_name='逾期等级')),
                ('kind', models.CharField(choices=[('initial', '初版立案'), ('escalation', '逾期升级'), ('correction', '人工更正')], max_length=16, verbose_name='版本类型')),
                ('reason', models.CharField(max_length=512, verbose_name='原因')),
                ('actor', models.CharField(blank=True, default='', max_length=64, verbose_name='操作人/任务')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assessment.penaltyunit', verbose_name='处罚单元')),
            ],
            options={
                'verbose_name': '处罚版本',
                'verbose_name_plural': '处罚版本',
                'ordering': ['penalty_id', 'version_no'],
            },
        ),
        migrations.CreateModel(
            name='ProblemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='事件编号')),
                ('contractor_name', models.CharField(blank=True, max_length=128, verbose_name='责任承包商快照')),
                ('category', models.CharField(choices=[('litter', '散落垃圾'), ('overflow', '垃圾桶满溢'), ('road_dirt', '路面污渍'), ('dead_corner', '卫生死角'), ('other', '其他问题')], max_length=20, verbose_name='问题类别')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='问题描述')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='发生位置')),
                ('occurred_at', models.DateTimeField(help_text='归属与 SLA 都以该时间为准，而不是录入时间', verbose_name='发生/拍摄时间')),
                ('status', models.CharField(choices=[('open', '待整改'), ('rectified', '已整改')], default='open', max_length=16, verbose_name='状态')),
                ('sla_hours', models.PositiveIntegerField(default=24, verbose_name='整改时限(小时)')),
                ('dedup_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='外部去重键')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assessment.cleaningcontract', verbose_name='责任合同（按发生时解析）')),
            ],
            options={
                'verbose_name': '问题事件',
                'verbose_name_plural': '问题事件',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='网格编号')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='网格名称')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='网格范围')),
            ],
            options={
                'verbose_name': '道路网格',
                'verbose_name_plural': '道路网格',
            },
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(verbose_name='是否通过')),
                ('comment', models.CharField(blank=True, max_length=512, verbose_name='复核意见')),
                ('reviewer', models.CharField(blank=True, default='', max_length=64, verbose_name='复核人')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='复核时间')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='assessment.penaltyunit', verbose_name='处罚单元')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='assessment.penaltyversion', verbose_name='被复核版本')),
            ],
            options={
                'verbose_name': '复核记录',
                'verbose_name_plural': '复核记录',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Rectification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=512, verbose_name='整改说明')),
                ('submitted_by', models.CharField(blank=True, default='', max_length=64, verbose_name='提交人')),
                ('submitted_at', models.DateTimeField(verbose_name='整改提交时间')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rectification', to='assessment.problemevent', verbose_name='问题事件')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rectifications', to='assessment.evidencephoto', verbose_name='整改后照片')),
            ],
            options={
                'verbose_name': '整改记录',
                'verbose_name_plural': '整改记录',
            },
        ),
        migrations.AddField(
            model_name='problemevent',
            name='grid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='assessment.roadgrid', verbose_name='所在网格'),
        ),
        migrations.AddField(
            model_name='problemevent',
            name='primary_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_of', to='assessment.evidencephoto', verbose_name='首报照片'),
        ),
        migrations.AddField(
            model_name='penaltyunit',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='penalty', to='assessment.problemevent', verbose_name='问题事件'),
        ),
        migrations.AddField(
            model_name='penaltyunit',
            name='locked_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_by_penalties', to='assessment.penaltyversion', verbose_name='最近锁定版本'),
        ),
        migrations.AddField(
            model_name='evidencephoto',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='assessment.problemevent', verbose_name='关联事件'),
        ),
        migrations.CreateModel(
            name='EscalationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(verbose_name='升级到等级')),
                ('reason', models.CharField(max_length=512, verbose_name='升级原因')),
                ('actor', models.CharField(blank=True, default='', max_length=64, verbose_name='执行任务')),
                ('ran_at', models.DateTimeField(verbose_name='执行时间(注入时钟)')),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='assessment.penaltyunit', verbose_name='处罚单元')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='assessment.penaltyversion', verbose_name='产生的处罚版本')),
            ],
            options={
                'verbose_name': '升级记录',
                'verbose_name_plural': '升级记录',
                'ordering': ['penalty_id', 'level'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamming_distance', models.PositiveSmallIntegerField(verbose_name='pHash汉明距离')),
                ('status', models.CharField(choices=[('pending', '待判定'), ('confirmed_duplicate', '确认同问题（挂接，不重复扣分）'), ('recurrence', '整改后复发（新建事件）'), ('different', '不同地点/不同问题（不合并）'), ('rejected', '误报忽略')], default='pending', max_length=24, verbose_name='判定状态')),
                ('decision_note', models.CharField(blank=True, max_length=256, verbose_name='判定说明')),
                ('decided_by', models.CharField(blank=True, max_length=64, verbose_name='判定人')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='判定时间')),
                ('matched_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_as', to='assessment.evidencephoto', verbose_name='相似照片')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='assessment.evidencephoto', verbose_name='新照片')),
            ],
            options={
                'verbose_name': '疑似重复候选',
                'verbose_name_plural': '疑似重复候选',
            },
        ),
        migrations.AddField(
            model_name='cleaningcontract',
            name='grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assessment.roadgrid', verbose_name='道路网格'),
        ),
        migrations.AddIndex(
            model_name='problemevent',
            index=models.Index(fields=['status', 'occurred_at'], name='assessment__status_bd2dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='problemevent',
            index=models.Index(fields=['contractor_name'], name='assessment__contrac_2ef9d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='penaltyversion',
            constraint=models.UniqueConstraint(fields=('penalty', 'version_no'), name='uniq_penalty_version_no'),
        ),
        migrations.AddConstraint(
            model_name='escalationrecord',
            constraint=models.UniqueConstraint(fields=('penalty', 'level'), name='uniq_escalation_level'),
        ),
        migrations.AddIndex(
            model_name='duplicatecandidate',
            index=models.Index(fields=['status'], name='assessment__status_dc7875_idx'),
        ),
        migrations.AddConstraint(
            model_name='duplicatecandidate',
            constraint=models.UniqueConstraint(fields=('photo', 'matched_photo'), name='uniq_candidate_pair'),
        ),
        migrations.AddIndex(
            model_name='cleaningcontract',
            index=models.Index(fields=['grid', 'valid_from', 'valid_to'], name='assessment__grid_id_96f9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningcontract',
            index=models.Index(fields=['contractor_name'], name='assessment__contrac_7b3938_idx'),
        ),
    ]
