# Generated by Django 4.2.30 on 2026-09-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duplicatecandidate',
            options={'ordering': ['-id'], 'verbose_name': '疑似重复候选', 'verbose_name_plural': '疑似重复候选'},
        ),
    ]
