# Generated by Django 4.2.30 on 2026-09-25 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_duplicatecandidate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_no', models.CharField(max_length=64, unique=True, verbose_name='设备编号')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='设备名称')),
                ('received_watermark', models.PositiveIntegerField(default=0, verbose_name='已连续接收序号')),
                ('applied_watermark', models.PositiveIntegerField(default=0, verbose_name='已连续处理序号')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近通信时间')),
            ],
            options={
                'verbose_name': '采集设备',
                'verbose_name_plural': '采集设备',
            },
        ),
        migrations.CreateModel(
            name='IngestedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.CharField(max_length=64, verbose_name='稳定操作号')),
                ('seq', models.PositiveIntegerField(verbose_name='设备内序号')),
                ('op_type', models.CharField(choices=[('photo_report', '问题照片立案'), ('rectification', '整改回执')], max_length=24, verbose_name='操作类型')),
                ('occurred_at', models.DateTimeField(help_text='归属/整改时间以该时间为准，而不是接收时间', verbose_name='业务发生时间')),
                ('payload', models.JSONField(default=dict, verbose_name='业务参数（含照片引用）')),
                ('payload_hash', models.CharField(editable=False, max_length=64, verbose_name='内容指纹(SHA256)')),
                ('batch_no', models.CharField(blank=True, default='', max_length=64, verbose_name='客户端批次号')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='assessment.collectiondevice', verbose_name='采集设备')),
            ],
            options={
                'verbose_name': '接收账本',
                'verbose_name_plural': '接收账本',
                'ordering': ['device_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='StagedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('media_key', models.CharField(max_length=64, verbose_name='客户端媒体键')),
                ('image', models.ImageField(upload_to='staged/%Y/%m/%d', verbose_name='图片文件')),
                ('sha256', models.CharField(editable=False, max_length=64, verbose_name='内容SHA256')),
                ('status', models.CharField(choices=[('staged', '已暂存（待引用）'), ('consumed', '已消费（已转为证据照片）')], default='staged', max_length=16, verbose_name='状态')),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staged_sources', to='assessment.evidencephoto', verbose_name='生成的证据照片')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staged_media', to='assessment.collectiondevice', verbose_name='采集设备')),
            ],
            options={
                'verbose_name': '暂存媒体',
                'verbose_name_plural': '暂存媒体',
            },
        ),
        migrations.CreateModel(
            name='OperationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('pending', '待处理（前序未齐）'), ('applied', '已执行'), ('ignored', '已忽略（业务幂等拒绝，如迟到的重复整改）'), ('failed', '执行失败（可重试）')], default='pending', max_length=16, verbose_name='处理状态')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='业务结果快照')),
                ('error', models.JSONField(blank=True, default=dict, verbose_name='失败信息')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='执行次数')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='assessment.ingestedoperation', verbose_name='接收账本')),
            ],
            options={
                'verbose_name': '操作回执',
                'verbose_name_plural': '操作回执',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='stagedmedia',
            constraint=models.UniqueConstraint(fields=('device', 'media_key'), name='uniq_staged_media_key'),
        ),
        migrations.AddIndex(
            model_name='operationreceipt',
            index=models.Index(fields=['status'], name='assessment__status_943704_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestedoperation',
            constraint=models.UniqueConstraint(fields=('device', 'op_id'), name='uniq_device_op_id'),
        ),
        migrations.AddConstraint(
            model_name='ingestedoperation',
            constraint=models.UniqueConstraint(fields=('device', 'seq'), name='uniq_device_seq'),
        ),
    ]
