# Generated by Django 4.2.30 on 2026-09-25 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_duplicatecandidate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceWatermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64, unique=True, verbose_name='设备编号')),
                ('received_through', models.PositiveIntegerField(default=0, verbose_name='已连续接收序号')),
                ('processed_through', models.PositiveIntegerField(default=0, verbose_name='已连续处理序号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备水位',
                'verbose_name_plural': '设备水位',
            },
        ),
        migrations.CreateModel(
            name='IngestMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=64, unique=True, verbose_name='媒体号(设备分配，全局唯一)')),
                ('device_id', models.CharField(db_index=True, max_length=64, verbose_name='上传设备')),
                ('image', models.ImageField(upload_to='ingest/%Y/%m/%d', verbose_name='图片文件')),
                ('phash', models.CharField(editable=False, max_length=64, verbose_name='感知哈希(hex)')),
                ('sha256', models.CharField(editable=False, max_length=64, verbose_name='内容指纹(sha256)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '采集媒体',
                'verbose_name_plural': '采集媒体',
            },
        ),
        migrations.CreateModel(
            name='IngestOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, verbose_name='设备编号')),
                ('operation_no', models.CharField(max_length=64, verbose_name='稳定操作号')),
                ('seq', models.PositiveIntegerField(verbose_name='设备内序号')),
                ('op_type', models.CharField(choices=[('report', '问题上报（照片+立案资料）'), ('rectify', '整改回执')], max_length=16, verbose_name='操作类型')),
                ('occurred_at', models.DateTimeField(help_text='合同归属/整改时间一律以它为准，而非到达时间', verbose_name='业务发生时间')),
                ('payload', models.JSONField(verbose_name='业务载荷')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='载荷指纹(sha256)')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
            options={
                'verbose_name': '接收账本',
                'verbose_name_plural': '接收账本',
                'ordering': ['device_id', 'seq'],
            },
        ),
        migrations.CreateModel(
            name='IngestReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理'), ('rejected', '业务拒绝'), ('failed', '处理失败')], default='pending', max_length=16, verbose_name='处理状态')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='业务结果')),
                ('error_code', models.CharField(blank=True, default='', max_length=64, verbose_name='错误码')),
                ('error_detail', models.CharField(blank=True, default='', max_length=512, verbose_name='错误说明')),
                ('status_note', models.CharField(blank=True, default='', max_length=256, verbose_name='状态备注')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='处理尝试次数')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='assessment.ingestoperation', verbose_name='账本操作')),
            ],
            options={
                'verbose_name': '接收回执',
                'verbose_name_plural': '接收回执',
            },
        ),
        migrations.AddIndex(
            model_name='ingestoperation',
            index=models.Index(fields=['device_id', 'seq'], name='assessment__device__c2a003_idx'),
        ),
        migrations.AddConstraint(
            model_name='ingestoperation',
            constraint=models.UniqueConstraint(fields=('device_id', 'operation_no'), name='uniq_ingest_op_no'),
        ),
        migrations.AddConstraint(
            model_name='ingestoperation',
            constraint=models.UniqueConstraint(fields=('device_id', 'seq'), name='uniq_ingest_op_seq'),
        ),
        migrations.AddField(
            model_name='ingestmedia',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_media', to='assessment.evidencephoto', verbose_name='已物化证据照片'),
        ),
        migrations.AddIndex(
            model_name='ingestreceipt',
            index=models.Index(fields=['status'], name='assessment__status_7fe2b7_idx'),
        ),
    ]
